src/ajax/urls.py
""" Ajax urls """
from django.urls import path
from .views import (
    tutorial_views,
    tutorial_comment_views,
)

app_name = "ajax"

urlpatterns = [
    path("tutorial/like", tutorial_views.like_view),
    path("tutorial/upvote", tutorial_views.upvote_view),
    path("tutorial/downvote", tutorial_views.downvote_view),
    path("tutorial_comment/like", tutorial_comment_views.like_view),
    path("tutorial_comment/upvote", tutorial_comment_views.upvote_view),
    path("tutorial_comment/downvote", tutorial_comment_views.downvote_view),
    path(
        "tutorial_comment/create",
        tutorial_comment_views.TutorialCommentCreateView.as_view(),
    ),
]

src/core/urls.py
import debug_toolbar

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("learning.urls")),
    path("auth/", include("authentication.url")),
    path("ajax/", include("ajax.urls")),
    path("user/", include("user.urls")),
    path("admin/", admin.site.urls, name="admin"),
    path("tinymce/", include("tinymce.urls")),
    # debug-toolbar
    path("__debug__/", include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/learning/urls.py
"""
    Learning urls
"""
from django.urls import path, re_path
from .views import HomeView, TutorialDetailsView, TutorialListView


app_name = "learning"
UNICODE_SLUG_REGEX = r"\w-"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    re_path(
        f"^tutorial/(?P<slug>[{UNICODE_SLUG_REGEX}]+)$",
        TutorialDetailsView.as_view(),
        name="tutorial",
    ),
    path(
        "tutorials_archive",
        TutorialListView.as_view(),
        name="tutorials_archive",
    ),
]

src/learning/models/category.py
""" Category mode """
from django.db import models
from django.utils.text import slugify
from django.core.exceptions import ValidationError
from django_lifecycle import LifecycleModel, hook, BEFORE_SAVE
from learning.querysets.category_queryset import CategoryQueryset


class Category(LifecycleModel):
    """Category model"""

    parent_category = models.ForeignKey(
        "self",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="child_categories",
        verbose_name="دسته بندی والد",
    )

    name = models.CharField("نام", unique=True, max_length=30)

    slug = models.SlugField(
        "اسلاگ", unique=True, max_length=50, blank=True, allow_unicode=True
    )

    is_active = models.BooleanField("فعال", default=True)

    # Validate data (for admin panel)
    def clean(self):
        if self.id == self.parent_category_id:
            raise ValidationError(
                "والد نمی تواند با دسته بندی فعلی یکسان باشد"
            )

    @hook(BEFORE_SAVE)
    def on_save(self):
        self.slug = slugify(self.name, allow_unicode=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"

    # Custom queryset
    objects: CategoryQueryset = CategoryQueryset.as_manager()

src/ajax/views/tutorial.py
from typing import Optional
from learning.models import (
    Tutorial,
    TutorialLike,
    TutorialUpVote,
    TutorialDownVote,
)
from ajax.views.shared import AjaxModelCreateDeleteView


__all__ = [
    "like_view",
    "upvote_view",
    "downvote_view",
]


class TutorialUserRelationCreateDeleteView(AjaxModelCreateDeleteView):
    tutorial: Optional[Tutorial] = None

    def prepare_objects(self):
        tutorial_id = self.data.get("tutorial_id")
        self.tutorial = (
            Tutorial.objects.active_and_confirmed_tutorials()
            .select_related("author")
            .get(pk=tutorial_id)
        )

    def get_objects(self):
        return self.model.objects.filter(
            user=self.request.user, tutorial=self.tutorial
        )

    def create_object(self):
        # Should automatically specify score and coin
        self.model.objects.create(
            user=self.request.user, tutorial=self.tutorial
        )


BaseView = TutorialUserRelationCreateDeleteView

like_view = BaseView.as_view(model=TutorialLike)
upvote_view = BaseView.as_view(model=TutorialUpVote)
downvote_view = BaseView.as_view(model=TutorialDownVote)

src/learning/views/home.py
""" Learn home view """
from django.http import HttpRequest
from django.shortcuts import render
from django.views.generic import View
from constance import config
from learning.models import Tutorial


class HomeView(View):
    """Home view"""

    def get(self, request: HttpRequest):
        carousel_count = config.LEARNING_HOME_CAROUSEL_ITEMS_COUNT

        tutorials = (
            Tutorial.objects.active_and_confirmed_tutorials()
            .only_main_fields()
            .annonate_comments_count()
        )

        latest_published_tutorials = tutorials.order_by(
            "-create_date",
        )[:carousel_count]

        most_liked_tutorials = tutorials.order_by(
            "-likes_count",
            "-create_date",
        )[:carousel_count]

        context = {
            "latest_published_tutorials": latest_published_tutorials,
            "most_liked_tutorials": most_liked_tutorials,
        }

        return render(request, "learning/home.html", context)

src/learning/views/tutorial.py
""" Tutorial view """
from django.http import HttpRequest
from django.utils.decorators import method_decorator
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from django.views.decorators.csrf import ensure_csrf_cookie
from constance import config
from learning.models import Tutorial, TutorialView


@method_decorator(ensure_csrf_cookie, name="dispatch")
class TutorialDetailsView(View):
    """Tutorial details view"""

    def get(self, request: HttpRequest, slug: str):
        recommendation_items_count = config.LEARNING_RECOMMENDATION_ITEMS_COUNT

        all_tutorials = Tutorial.objects.active_and_confirmed_tutorials()

        tutorial: Tutorial = get_object_or_404(
            all_tutorials.select_related("author")
            .prefetch_related("tags")
            .prefetch_active_categories()
            .prefetch_active_confirmed_comments(),
            slug=slug,
        )

        related_tutorials = all_tutorials.get_related_tutorials(
            tutorial, recommendation_items_count
        ).only_main_fields()

        # Check is user logged in and liked this tutorial
        liked_by_current_user = (
            request.user.is_authenticated
            and tutorial.likes.filter(user=request.user).exists()
        )

        latest_tutorials = all_tutorials.order_by("-create_date")[
            :recommendation_items_count
        ]
        most_popular_tutorials = all_tutorials.order_by(
            "-likes_count", "-create_date"
        )[:recommendation_items_count]

        context = {
            "tutorial": tutorial,
            "liked_by_current_user": liked_by_current_user,
            "comments": tutorial.comments.all(),
            "tags": tutorial.tags.all(),
            # If there wasn't any related_tutorial use latest_tutorials instead
            "related_tutorials": related_tutorials or latest_tutorials,
            "latest_tutorials": latest_tutorials,
            "most_popular_tutorials": most_popular_tutorials,
        }

        self.record_tutorial_view(tutorial)
        return render(request, "learning/tutorial.html", context)

    def record_tutorial_view(self, tutorial: Tutorial):
        """Records tutorial's view.

        Args:
            tutorial (Tutorial): Visited tutorial
        """
        user = self.request.user
        if (
            user.is_authenticated
            and not tutorial.views.filter(user=user).exists()
        ):
            # Will automatically specify score and coin
            TutorialView.objects.create(user=user, tutorial=tutorial)

src/learning/views/tutorials_archive.py
from django.views.generic import ListView
from constance import config
from learning.models import Tutorial, Category
from learning.filters import TutorialArchiveFilterSet


class TutorialListView(ListView):
    model = Tutorial
    template_name = "learning/tutorials_archive.html"

    page_kwarg = "page"
    context_object_name = "tutorials"

    def get_paginate_by(self, queryset):
        return config.LEARNING_TUTORIAL_ARCHIVE_PAGINATE_BY

    def get_queryset(self):
        # All confirmed and active tutorials
        tutorials = (
            Tutorial.objects.order_by("-create_date")
            .only_main_fields()
            .active_and_confirmed_tutorials()
        )

        # Filter and order tutorials, then annonate comments_count
        tutorials = TutorialArchiveFilterSet(
            self.request.GET, tutorials
        ).qs.annonate_comments_count()

        return tutorials

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        category_slug = self.request.GET.get("category")
        if category_slug:
            context["category"] = (
                Category.objects.active_categories()
                .filter(slug=category_slug)
                .first()
            )

        return context

src/user/views/home.py
from django.http import HttpRequest
from django.shortcuts import render
from django.views.generic import View
from constance import config
from authentication.models import User
from shared.models import ConfirmStatusChoices
from shared.statistics import UserPanelStatistics
from learning.models import Tutorial, TutorialView


class HomeView(View):
    def get(self, request: HttpRequest):
        latest_user_tutorials_count = 5

        latest_user_tutorials = (
            Tutorial.objects.filter(author=request.user)
            .prefetch_active_categories()
            .order_by("-create_date")[:latest_user_tutorials_count]
        )

        context = {
            "ConfirmStatusChoices": ConfirmStatusChoices,
            "statistics": self.get_statistics(),
            "latest_user_tutorials": latest_user_tutorials,
        }

        return render(request, "user/home.html", context)

    def get_statistics(self):
        user: User = self.request.user
        last_months_count = config.USER_PANEL_STATISTICS_LAST_MONTH_COUNT

        view_statistics = list(
            TutorialView.objects.filter(
                tutorial__author=user
            ).active_confirmed_tutorials()
            # get_last_months_count_statistics yields result
            .get_last_months_count_statistics(last_months_count)
        )

        tutorial_statistics = (
            Tutorial.objects.filter(author=user)
            .active_and_confirmed_tutorials()
            .aggregate_statistics()
        )

        return UserPanelStatistics(user, tutorial_statistics, view_statistics)

src/user/views/tutorials.py
from django.forms import ModelForm
from django.contrib import messages
from django.views.generic import CreateView, UpdateView
from django.shortcuts import reverse, redirect
from django.core.exceptions import ImproperlyConfigured
from django_tables2 import SingleTableView
from constance import config
from user.tables import TutorialTable, TutorialUserRelationsTable
from user.forms import TutorialForm
from learning.models import Tutorial, TutorialView, TutorialLike
from shared.views.generic import (
    DynamicModelFieldDetailView,
    DeleteDeactivationView,
)


SUCCESS_VIEW_NAME = "user:tutorials"


def get_paginate_by():
    """Note: defining paginate_by as a function is necessary
    to ensure it changes immediately."""
    return config.USER_PANEL_PAGINATE_BY


def get_tutorials_queryset(user):
    return (
        Tutorial.objects.filter(author=user)
        .select_related("author")
        .prefetch_related("tags", "categories")
    )


class TutorialListView(SingleTableView):
    table_class = TutorialTable
    template_name = "user/shared/list.html"

    @property
    def paginate_by(self):
        """Note: SingleTableView doesn't use get_paginate_by()
        currently. thus, defining paginate_by as a property
        is necessary to ensure it changes immediately.
        """
        return get_paginate_by()

    def get_queryset(self):
        return get_tutorials_queryset(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["create_url"] = "user:tutorial_create"
        return context


class TutorialDetailView(DynamicModelFieldDetailView):
    def get_tags(self):
        return "، ".join([str(tag) for tag in self.object.tags.all()])

    get_tags.short_description = "کلمات کلیدی"

    template_name = "user/shared/details.html"
    additional_content = [get_tags]
    fields = (
        "title",
        "slug",
        "short_description",
        "body",
        "create_date",
        "last_edit_date",
        "confirm_status",
        "categories",
        get_tags,
        "image",
        "user_views_count",
        "up_votes_count",
        "down_votes_count",
        "likes_count",
        "is_edited",
        "is_active",
    )

    def get_queryset(self):
        return get_tutorials_queryset(self.request.user)


class TutorialCreateView(CreateView):
    template_name = "user/shared/create_update.html"

    form_class = TutorialForm

    def form_valid(self, form: TutorialForm):
        tutorial: Tutorial = form.save(commit=False)
        # Set tutorial author
        tutorial.author = self.request.user
        # Save tutorial
        tutorial.save()

        # Save many-to-many relations (categories here)
        form.save_m2m()
        # Save tutorial tags
        form.save_tags()

        messages.success(
            self.request, f'آموزش "{tutorial.title}" با موفقیت افزوده شد'
        )
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse(SUCCESS_VIEW_NAME)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tagsinput_required"] = True
        return context


class TutorialUpdateView(UpdateView):
    template_name = "user/shared/create_update.html"

    form_class = TutorialForm

    def get_queryset(self):
        return get_tutorials_queryset(self.request.user)

    def form_valid(self, form: ModelForm):
        tutorial: Tutorial = form.save()

        messages.success(
            self.request, f'آموزش "{tutorial.title}" با موفقیت ویرایش شد'
        )
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse(SUCCESS_VIEW_NAME)


class TutorialDeleteDeactivateView(DeleteDeactivationView):
    template_name = "user/shared/delete.html"
    context_object_name = "tutorial"

    def get_queryset(self):
        return get_tutorials_queryset(self.request.user)

    def get_success_url(self):
        return reverse(SUCCESS_VIEW_NAME)


class TutorialRelationsTableViewMixin:
    model = None
    table_class = TutorialUserRelationsTable

    default_ordering = ("-create_date",)
    template_name = "user/shared/list.html"

    @property
    def paginate_by(self):
        return get_paginate_by()

    def get_queryset(self):
        if not self.model:
            raise ImproperlyConfigured(
                "You should set model or implement get_queryset() "
                "first to use TutorialRelationsTableViewMixin"
            )

        return (
            self.model.objects.order_by(*self.default_ordering)
            .select_related("user", "tutorial")
            .active_confirmed_tutorials()
        )


class TutorialsViewedByOthersListView(
    TutorialRelationsTableViewMixin, SingleTableView
):
    model = TutorialView

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(tutorial__author=self.request.user)


class TutorialsLikedByOthersListView(
    TutorialRelationsTableViewMixin, SingleTableView
):
    model = TutorialLike

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(tutorial__author=self.request.user)


class TutorialsLikedByMeListView(
    TutorialRelationsTableViewMixin, SingleTableView
):
    model = TutorialLike

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(user=self.request.user)

src/learning/templates/learning/tutorials_archive.html
{% extends 'base.html' %}
{% load static %}
{% load image_utils %}
{% load basic_utils %}


{% block title %} آرشیو آموزش ها{% if category %}ی "{{ category.name }}"{% endif %} {% endblock title %}


{% block content %}

    <!-- All tutorials -->
    <section class=" my-6">

        <!-- Heading -->
        <section class="jumbotron rounded-0 bg-header-1">

            <!-- Breadcrumb -->
            <section class="float-right">
                <ul class="breadcrumb bg-light d-inline-flex">
                    <li class="breadcrumb-item">
                        <a href="/">خانه</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a {% if category %} href="{% url 'learning:tutorials_archive' %}" {% endif %}>آموزش ها</a>
                    </li>

                    {% if category %}
                        <li class="breadcrumb-item">
                            <span>{{ category.name }}</span>
                        </li>
                    {% endif %}

                </ul>
            </section>
            <!-- End Breadcrumb -->

            <!-- Header -->
            <section class="float-left">
                <h1 class="text-shadow-dark-1 text-white">آرشیو آموزش ها{% if category %}ی "{{ category.name }}"{% endif %}</h1>
            </section>
            <!-- End Header -->

            <section class="clearfix"></section>
        </section>
        <!-- End Heading -->




        <!-- Filters -->
        <section class="container bg-lightblue py-3 rounded">

            <!-- Filters form -->
            <form id="filter-form" action="{% url 'learning:tutorials_archive' %}" method="GET" class="mb-0">
                <section class="form-group row text-center">

                    
                    <input name="category" type="hidden">


                    <!-- Orderby Name, Time, and ... -->
                    <section class="col-lg-4 col-sm-6 mt-2">
                        <label for="order_by">مرتب سازی بر اساس</label>
                        <select name="order_by" id="order_by" class="custom-select">
                            <option value="create_date">زمان انتشار</option>
                            <option value="likes_count">لایک ها</option>
                            <option value="user_views_count">بازدید</option>
                            <option value="title">عنوان</option>
                        </select>
                    </section>
                    <!-- End Orderby Name, Time, and -->

                    <!-- Orderby Asending,Decending -->
                    <section class="col-lg-3 col-sm-6 mt-2">
                        <label>نوع مرتب سازی</label>
                        <br>
                        <label for="ascending" class="mr-2">
                            <input name="ascending_or_descending" value="ascending" id="ascending" type="radio" class="custom-radio"> صعودی
                        </label>
                        <label for="decending" class="ml-2">
                            <input name="ascending_or_descending" value="descending" id="decending" type="radio" class="custom-radio" checked="true"> نزولی
                        </label>
                    </section>
                    <!-- End Orderby Asending,Decending -->

                    <!-- Search -->
                    <section class="col-lg-3 col-sm-12 mt-2">
                        <label for="search">جستجوی عبارت</label>
                        <br>
                        <input type="text" name="search" id="search" name='search' placeholder="عبارت مورد نظر را وارد کنید" class="form-control">
                    </section>
                    <!-- End Search -->

                    <input name="page" type="hidden" value="{{ page_obj.number }}">

                    <!-- Submit button -->
                    <section class="col-lg-2 d-flex flex-column justify-content-end mt-3">
                        <button type="submit" class="btn btn-success w-100">جستجو</button>
                    </section>
                    <!-- End Submit button -->

                </section>
            </form>
            <!-- End Filters form -->

        </section>
        <!-- End Filters -->








        <!-- Tutorials -->

        <section class="container mt-3">
            <section class="row justify-content-center">


                {% for tutorial in tutorials %}
                    <!-- Single tutorial -->
                    <article class="col-lg-4 col-sm-6 col-12 my-3">
                        <section class="card bg-whiteblue">
                            <section class="card-header">
                                <img src="{{ tutorial.image|image_url }}" class="w-100" alt="{{ tutorial.title }}">
                            </section>

                            <section class="card-body px-3 pb-3 text-center">
                                <h5>
                                    <a href="{% url 'learning:tutorial' tutorial.slug %}">
                                        {{ tutorial.title }}
                                    </a>
                                </h5>
                                <p class="text-muted">
                                    {{ tutorial.short_description|truncatewords:5|safe }}
                                </p>
                            </section>

                            <section class="card-footer bg-whiteblue text-left">
                                <section class="float-left">
                                    <i class="fa fa-comments-o"></i>
                                    {{ tutorial.comments_count }}
                                </section>
                                <section class="float-right">
                                    {{ tutorial.likes_count }}
                                    <i class="fa fa-heart-o"></i>
                                </section>
                            </section>
                        </section>
                    </article>
                    <!-- End Single tutorial -->
                {% empty %}
                    <p>موردی یافت نشد</p>
                {% endfor %}




            </section>
        </section>

        <!-- End Tutorials -->



        <!-- Pagination -->
        <section class="d-flex justify-content-center mt-3">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a onclick="change_page(1)" class="page-link">اول</a></li>
                    <li class="page-item"><a onclick="change_page({{page_obj.previous_page_number}})" class="page-link">&laquo;</a></li>
                {% endif %}

                {% for page_num in page_obj.paginator.num_pages|page_range %}
                    <li class="page-item {% if page_num == page_obj.number %}active{% endif %}">
                        <a onclick="change_page({{page_num}})" class="page-link">{{page_num}}</a>
                    </li>
                {% endfor %}
                
                {% if page_obj.has_next %}
                    <li class="page-item"><a onclick="change_page({{page_obj.next_page_number}})" class="page-link">&raquo;</a></li>
                    <li class="page-item"><a onclick="change_page({{page_obj.paginator.num_pages}})" class="page-link">آخر</a></li>
                {% endif %}
            </ul>
        </section>
        <!-- End Pagination -->




    </section>
    <!-- End All tutorials -->

{% endblock content %}

{% block extra_scripts %}
<script>
    searchParams = (new URL(window.location.href)).searchParams
    
    searchParams.forEach((x, y) =>{
        node = document.getElementsByName(y)[0]
        
        if(node.type != "radio"){
            node.value = x
        }
    });

    ascending_or_descending = searchParams.get('ascending_or_descending')
    if(ascending_or_descending != null){
        document.querySelectorAll('input[name="ascending_or_descending"]').forEach(i => i.checked=false)
        document.querySelector('input[name="ascending_or_descending"][value="' + ascending_or_descending + '"]').checked=true
    }

    function change_page(page){
        document.getElementsByName('page')[0].value = page;
        document.getElementById('filter-form').submit();
    }

</script>
{% endblock extra_scripts %}